# Allow manually specifying an older version during configuration, if not, default to current.
set(BEME_LATEST_VERSION_INT 251200)

if(NOT PROJECT_VERSION OR PROJECT_VERSION STREQUAL "latest")
  math(EXPR BEME_LATEST_MAJOR "${BEME_LATEST_VERSION_INT} / 10000")
  math(EXPR BEME_LATEST_MINOR "(${BEME_LATEST_VERSION_INT} % 10000) / 100")
  math(EXPR BEME_LATEST_PATCH "${BEME_LATEST_VERSION_INT} % 100")
  set(PROJECT_VERSION "${BEME_LATEST_MAJOR}.${BEME_LATEST_MINOR}.${BEME_LATEST_PATCH}")
endif()
